#!/usr/bin/env python3
# copied from electrum
# adapted to electrum-ravencoin by kralverde
# adapted to raven-trader-pro by fdov

import os
import subprocess
import io
import zipfile
import sys

try:
    import requests
except ImportError as e:
    sys.exit(f"Error: {str(e)}. Try 'sudo python3 -m pip install <module-name>'")

os.chdir(os.path.dirname(os.path.realpath(__file__)))
os.chdir('..')

cmd = "find . -type f -name '*.py' -o -name '*.kv'"

files = subprocess.check_output(cmd, shell=True)

with open("app.fil", "wb") as f:
    f.write(files)

logging.info("Found {} files to translate".format(len(files.splitlines())))

# Generate fresh translation template
if not os.path.exists('locale'):
    os.mkdir('locale')
cmd = 'xgettext -s --from-code UTF-8 --language Python --no-wrap -f app.fil --output=locale/messages.pot'
logging.info('Generate template')
os.system(cmd)
